### ISSUE TITLE
[IR: turbine go] Cleanup turbine v1 path is turbine go

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/turbine-go#111]
## Metadata

Main task: https://github.com/meroxa/product/issues/492

[Intermediate Representation RFC](https://www.notion.so/meroxa/Turbine-Intermediate-Representation-98ee81e4be5648e2a9794b7cb75c9eae).

[Addendum](https://www.notion.so/meroxa/Addendum-Turbine-Intermediate-Representation-RFC-42649002b5fd41efacdcb93f36b61231)

## Context

Remove code paths that allowed creating artifacts via API calls in turbine.

## Acceptance  

- [ ] Remove non IR codepath https://github.com/meroxa/turbine-go/blob/e6470e58b719a02c4314da4e512afef7078c4fe8/runner/platform.go#L53
- [ ] Remove meroxa-go dependency https://github.com/meroxa/turbine-go/blob/e6470e58b719a02c4314da4e512afef7078c4fe8/go.mod#L10

**Comment by jkayh** [comment]
closing this for now until reprioritized linked in this [epic](https://github.com/meroxa/product/issues/690) for tracking.

**Comment by jkayh** [comment]
closing this for now until reprioritized linked in this [epic](https://github.com/meroxa/product/issues/690) for tracking.
